### ISSUE TITLE
Change data-creation and multiplexing

### ISSUE THREAD

**Issue by arnegue** [arnegue/nmea_seatalk_multiplexer#3]
Currently this program's focus is on NMEA-messages: Receiving NMEA-Messages on one device and forwarding it to another (without parsing whatsoever).
Only Seatalk-Mesages are getting parsed so that they may get put into another NMEA-Message and getting send to a NMEA-device. And then only if there is a one-to-one-datagram on each side. This is done throught inheritance. (Seatalk-datagram derives from nmea-datagram).

But there are some limitations.
E.g:
NMEA's datagram (RMC) needs more than one Seatalk-Datagram for its message: There are two seatalk-datagrams for one position: LatitudePosition (0x50) and LongitudePosition (0x51). One for time, one for date, one for speed....

### TODOs and thoughts (will be edited through the whole process)
- [ ] Write a "database" of the current ship "status" (~every datatype there is)
- [ ] Write a publish/subscribe model to these values on the database
- [ ] Add a timestamp (max-age) to the values
- [ ] Fill these data from nmea- and seatalk-datagrams
- [ ] Get rid of inheritance: Seatalk-datagram from NMEA-datagram (and use super() constructor instead)
- [ ] Get rid of inheritance: Seatalk-Exceptions from NMEA-Exceptions
- [ ] In devices, do not subscribe from other devices but rather from specific messages [nmea subscribe specific to nmea-datagrams, seatalk to specific seatalk-datagrams
- [ ] If wanted: subscribe for every other datagram, which is not parsable (Seatalk doesn't have this feature yet)
- [ ] Change SpecialDevices (SetTimeDevice from ShipData, so it doesn't depend on NMEA: Seatalk has a Date/Time object too)
- [ ] Rename get_seatalk_datagram to get_datragram (SeatalkDatagram is a DeviceClass, that function only returns bytearray)
